// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SafeLinkApi.Data;

#nullable disable

namespace SafeLinkApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250606144053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeLinkApi.Models.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("EmitidoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EMITIDO_EM");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_NIVEL_RISCO");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.ToTable("TB_ALERTA", (string)null);
                });

            modelBuilder.Entity("SafeLinkApi.Models.EventoNatural", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO_NATURAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<DateTime>("Ocorrencia")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_OCORRENCIA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_TIPO");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.ToTable("TB_EVENTO_NATURAL", (string)null);
                });

            modelBuilder.Entity("SafeLinkApi.Models.PrevisaoRisco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PREVISAO_RISCO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("Fonte")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_FONTE");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_GERADO_EM");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("NivelPrevisto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_NIVEL_PREVISTO");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.ToTable("TB_PREVISAO_RISCO", (string)null);
                });

            modelBuilder.Entity("SafeLinkApi.Models.Regiao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SG_ESTADO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VL_LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VL_LONGITUDE");

                    b.Property<string>("NomeRegiao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NM_REGIAO");

                    b.HasKey("Id");

                    b.ToTable("TB_REGIAO", (string)null);
                });

            modelBuilder.Entity("SafeLinkApi.Models.RelatoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RELATO_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DataRelato")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_RELATO");

                    b.Property<long>("IdRegiao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_MENSAGEM");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_RELATO_USUARIO", (string)null);
                });

            modelBuilder.Entity("SafeLinkApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_ROLE");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_SENHA");

                    b.HasKey("Id");

                    b.ToTable("TB_USER", (string)null);
                });

            modelBuilder.Entity("SafeLinkApi.Models.Alerta", b =>
                {
                    b.HasOne("SafeLinkApi.Models.Regiao", "Regiao")
                        .WithMany("Alertas")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("SafeLinkApi.Models.EventoNatural", b =>
                {
                    b.HasOne("SafeLinkApi.Models.Regiao", "Regiao")
                        .WithMany("EventosNaturais")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("SafeLinkApi.Models.PrevisaoRisco", b =>
                {
                    b.HasOne("SafeLinkApi.Models.Regiao", "Regiao")
                        .WithMany("PrevisoesRisco")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("SafeLinkApi.Models.RelatoUsuario", b =>
                {
                    b.HasOne("SafeLinkApi.Models.Regiao", "Regiao")
                        .WithMany("RelatosUsuario")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeLinkApi.Models.User", "Usuario")
                        .WithMany("RelatosUsuario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SafeLinkApi.Models.Regiao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("EventosNaturais");

                    b.Navigation("PrevisoesRisco");

                    b.Navigation("RelatosUsuario");
                });

            modelBuilder.Entity("SafeLinkApi.Models.User", b =>
                {
                    b.Navigation("RelatosUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
